### ISSUE TITLE
Referential integrity should be checked

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/backstage-entity-validator#30]
There are cases where a Backstage metadata file will fail to import because of a group or other dependency that doesn't exist.

For example, if `Group:engineering` doesn't exist in the Backstage instance we try to import this YAML into, the import will fail.

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-1
  description: A service for testing Backstage functionality
  annotations:
    github.com/project-slug: RoadieHQ/sample-service
spec:
  type: service
  owner: Group:engineering
  lifecycle: experimental
```

The validator should detect these failures as part of its standard suite of checks.
