### ISSUE TITLE
Locations fail without `spec` attribute which is inconsistent with docs

### ISSUE THREAD

**Issue by Counterfly** [RoadieHQ/backstage-entity-validator#34]
## Version:

0.3.7

## What happened:

validator fails with:
```
Your catalog file(s) is/are not valid:

There was an error verifying entity-templates/catalog-info-2.yml:
TypeError: <root> should have required property 'spec' - missingProperty: spec
```

## Expected behavior:

the validator should succeed (no errors should arise).  This should happen because of [these backstage docs](https://backstage.io/docs/features/software-catalog/descriptor-format#kind-location) which show `spec` as optional

## Additional Information:

here is a sample Location (catalog-info.yaml)
```
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: todo-example-project
```

a fix was to add a dummy `spec`:
```
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: todo-example-project
spec:
  type: dummy
```
