### ISSUE TITLE
Support Gitlab Pipelines

### ISSUE THREAD

**Issue by tillepille** [RoadieHQ/backstage-entity-validator#59]
## Describe Request:

I would love to use the validator in my GitLab pipelines.

At the moment I have to maintain my own image, maybe you could support this by adding a Docker build to the pipeline and provide it as an image in your existing Dockerhub org?

I would be happy to create a PR for a Dockerfile and the initial action but of course can't configure the credentials for the org.

## Examples:

```yml
validate:
  stage: test
  image: roadiehq/backstage-entity-validator
  script:
  - validate-entity file1.yaml
```
## Supporting Documentation Links:

- https://github.com/marketplace/actions/build-and-push-docker-images
