### ISSUE TITLE
techdocs default mkdoc.yaml

### ISSUE THREAD

**Issue by wrighbr** [RoadieHQ/backstage-entity-validator#69]
## Version:

v0.3.11

## What happened:
Starting from version 1.11.0, Backstage now includes a default mkdoc.yaml file. https://github.com/backstage/backstage/pull/15417

https://github.com/backstage/backstage/blob/9e826a3f8796b5f5bfd2f2eb31406c9bec327bdd/docs/releases/v1.11.0-changelog.md?plain=1#L833

When the following annotation is set, the following error message is displayed `Failed to validate catalog-info.yaml: Error: Techdocs annotation specifies "dir" but file under mkdocs.yaml|mkdocs.yml not found`
```
apiVersion: backstage.io/v1alpha1
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
```
## Expected behavior:
The validation should pass when the above annotations are set, as the default mkdocs.yaml file will be utilised.
