### ISSUE TITLE
DependsOn resource syntax error not detected

### ISSUE THREAD

**Issue by christoph-buente** [RoadieHQ/backstage-entity-validator#78]
## What happened:

I created a catalog-info.yml file with a service that declared a dependency on a resource. However, I had a syntax in it and backstage actually complained about it when importing. However, the validator did not.

The mistake I made was writing this:

```
spec:
  type: service
  lifecycle: production
  owner: team-name
  dependsOn:
    - resource/default:kinesis-stream # wrong
    - resource:default/kinesis-stream # correct
```

## Expected behavior:

I would expect the same error message that backstage gives:
`Entity reference "resource/default:kinesis-stream" had missing or empty kind (e.g. did not start with "component:" or similar)`
